name: Build, sign and deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    name: build
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 8

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: ${{ env.IMAGE }}

      - name: NAIS SLSA Provenance Action
        uses: nais/salsa-action@v0.0.1-beta
        with:
          ecosystem: gradle
          key: ${{ secrets.SALSA_KMS_KEY }}
          image: ${{ env.IMAGE }}@${{ steps.docker_build.outputs.digest }}